baseURL: 'https://arch.fail'
theme: risotto
title: sirius
author: Pratyush Desai
paginate: 3
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: true
sectionPagesMenu: main
params:
  noindex: false
  theme:
    palette: rosepine
  about:
    title: pratyush desai
    description: No description set
    logo: images/shodandos.jpg
  socialLinks:
    - icon: fa-brands fa-github
      title: GitHub
      url: 'https://github.com/mogad0n'
    - icon: fa-brands fa-git-alt
      title: Gitea
      url: 'https://git.com.de/pratyush'
    - icon: fa-solid fa-envelope
      title: Email
      url: 'mailto:pratyush.desai@liberta.casa'
    - icon: fa-brands fa-mastodon
      title: Mastodon
      url: 'https://fosstodon.org/@mogad0n'
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 10
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 10
taxonomies:
  category: categories
  tag: tags
  series: series
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 3
    ordered: true
